/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;
import Controller.Controladora;
import Modelo.ListaHerramientas;
import Modelo.ListaManoDeObra;
import Modelo.Material;
import Modelo.ListaMateriales;
import java.awt.Color;
import javax.swing.JOptionPane;
import java.util.Iterator;

import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;
import org.json.simple.parser.ParseException;

/**
 *
 * @author laura
 */
public class AgregarMaterial extends javax.swing.JFrame {

    Controladora control = new Controladora(this);
    ListaMateriales mat = new ListaMateriales();
    ListaManoDeObra mob = new ListaManoDeObra();
    ListaHerramientas mhr = new ListaHerramientas();
    StringBuilder errores = new StringBuilder();
    
    public AgregarMaterial() {
        initComponents();
        mat.agregarMaterial();
        mob.agregarManoDeObra();
        mhr.agregarHerramienta();
        control.iniciaVentana(this);
    }
    
    public AgregarMaterial(ListaMateriales mati, ListaManoDeObra mo, ListaHerramientas mh) {
        if(mati.vertamanomat()==0){
            mati.agregarMaterial();
        }
        if(mo.vertamanomob()==0){
            mo.agregarManoDeObra();
        }
        if(mh.vertamanoher()==0){
            mh.agregarHerramienta();
        }
        mat=mati;
        mob=mo;
        mhr=mh;
        initComponents();
        control.iniciaVentana(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    public boolean validarDato(String dato, String mensaje) {
        boolean error = false;
        if (dato == null || dato.isEmpty() || dato.equals("Ingrese "+mensaje)){
            error = true;
        }
        return error;
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnAgregarMaterial = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnMateriales = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnHerramientas = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnAgregarHerramienta = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnManoDeObra = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnAgregarManoDeObra = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        nombretxt = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        colortxt = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        proveedortxt = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel17 = new javax.swing.JLabel();
        funciontxt = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel18 = new javax.swing.JLabel();
        costotxt = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel19 = new javax.swing.JLabel();
        unidadtxt = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        btnAgregar = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        errorNombre = new javax.swing.JLabel();
        errorColor = new javax.swing.JLabel();
        errorMedida = new javax.swing.JLabel();
        errorProveedor = new javax.swing.JLabel();
        errorFuncion = new javax.swing.JLabel();
        errorCosto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(84, 33, 89));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo.png"))); // NOI18N

        btnAgregarMaterial.setBackground(new java.awt.Color(85, 55, 118));
        btnAgregarMaterial.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Agregar Material.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Agregar Material");

        javax.swing.GroupLayout btnAgregarMaterialLayout = new javax.swing.GroupLayout(btnAgregarMaterial);
        btnAgregarMaterial.setLayout(btnAgregarMaterialLayout);
        btnAgregarMaterialLayout.setHorizontalGroup(
            btnAgregarMaterialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAgregarMaterialLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnAgregarMaterialLayout.setVerticalGroup(
            btnAgregarMaterialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAgregarMaterialLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(btnAgregarMaterialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        btnMateriales.setBackground(new java.awt.Color(83, 43, 100));
        btnMateriales.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMateriales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMaterialesMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/materiales.png"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Materiales");

        javax.swing.GroupLayout btnMaterialesLayout = new javax.swing.GroupLayout(btnMateriales);
        btnMateriales.setLayout(btnMaterialesLayout);
        btnMaterialesLayout.setHorizontalGroup(
            btnMaterialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnMaterialesLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnMaterialesLayout.setVerticalGroup(
            btnMaterialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnMaterialesLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(btnMaterialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        btnHerramientas.setBackground(new java.awt.Color(83, 43, 100));
        btnHerramientas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHerramientas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHerramientasMouseClicked(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/herramientas.png"))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Herramientas");

        javax.swing.GroupLayout btnHerramientasLayout = new javax.swing.GroupLayout(btnHerramientas);
        btnHerramientas.setLayout(btnHerramientasLayout);
        btnHerramientasLayout.setHorizontalGroup(
            btnHerramientasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnHerramientasLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnHerramientasLayout.setVerticalGroup(
            btnHerramientasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnHerramientasLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(btnHerramientasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        btnAgregarHerramienta.setBackground(new java.awt.Color(83, 43, 100));
        btnAgregarHerramienta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregarHerramienta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarHerramientaMouseClicked(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/herramienta (2).png"))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Agregar Herramienta");

        javax.swing.GroupLayout btnAgregarHerramientaLayout = new javax.swing.GroupLayout(btnAgregarHerramienta);
        btnAgregarHerramienta.setLayout(btnAgregarHerramientaLayout);
        btnAgregarHerramientaLayout.setHorizontalGroup(
            btnAgregarHerramientaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAgregarHerramientaLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnAgregarHerramientaLayout.setVerticalGroup(
            btnAgregarHerramientaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAgregarHerramientaLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(btnAgregarHerramientaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        btnManoDeObra.setBackground(new java.awt.Color(83, 43, 100));
        btnManoDeObra.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnManoDeObra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnManoDeObraMouseClicked(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/mano de obra.png"))); // NOI18N

        jLabel11.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Mano de Obra");

        javax.swing.GroupLayout btnManoDeObraLayout = new javax.swing.GroupLayout(btnManoDeObra);
        btnManoDeObra.setLayout(btnManoDeObraLayout);
        btnManoDeObraLayout.setHorizontalGroup(
            btnManoDeObraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnManoDeObraLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnManoDeObraLayout.setVerticalGroup(
            btnManoDeObraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnManoDeObraLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(btnManoDeObraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        btnAgregarManoDeObra.setBackground(new java.awt.Color(83, 43, 100));
        btnAgregarManoDeObra.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregarManoDeObra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarManoDeObraMouseClicked(evt);
            }
        });

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/modificar MO.png"))); // NOI18N

        jLabel13.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Agregar Mano de Obra");

        javax.swing.GroupLayout btnAgregarManoDeObraLayout = new javax.swing.GroupLayout(btnAgregarManoDeObra);
        btnAgregarManoDeObra.setLayout(btnAgregarManoDeObraLayout);
        btnAgregarManoDeObraLayout.setHorizontalGroup(
            btnAgregarManoDeObraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAgregarManoDeObraLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addContainerGap(43, Short.MAX_VALUE))
        );
        btnAgregarManoDeObraLayout.setVerticalGroup(
            btnAgregarManoDeObraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAgregarManoDeObraLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(btnAgregarManoDeObraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnMateriales, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnAgregarMaterial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnHerramientas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnAgregarHerramienta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnManoDeObra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(btnAgregarManoDeObra, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMateriales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAgregarMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnHerramientas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAgregarHerramienta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnManoDeObra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAgregarManoDeObra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel14.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/material2.png"))); // NOI18N
        jLabel14.setText("Nombre del Material:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(267, 93, -1, -1));

        nombretxt.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        nombretxt.setForeground(new java.awt.Color(204, 204, 204));
        nombretxt.setText("Ingrese el nombre");
        nombretxt.setBorder(null);
        nombretxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nombretxtMouseClicked(evt);
            }
        });
        jPanel1.add(nombretxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 131, 210, -1));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 159, 176, 10));

        jLabel15.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/color.png"))); // NOI18N
        jLabel15.setText("Color:");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(267, 208, -1, -1));

        colortxt.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        colortxt.setForeground(new java.awt.Color(204, 204, 204));
        colortxt.setText("Ingrese el color");
        colortxt.setBorder(null);
        colortxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                colortxtMouseClicked(evt);
            }
        });
        jPanel1.add(colortxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 252, 178, -1));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 280, 178, 10));

        jLabel16.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/proveedor.png"))); // NOI18N
        jLabel16.setText("Proveedor:");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(267, 334, -1, -1));

        proveedortxt.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        proveedortxt.setForeground(new java.awt.Color(204, 204, 204));
        proveedortxt.setText("Ingrese el proveedor");
        proveedortxt.setBorder(null);
        proveedortxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                proveedortxtMouseClicked(evt);
            }
        });
        jPanel1.add(proveedortxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 384, -1, -1));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 407, 178, 10));

        jLabel17.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/funcion.png"))); // NOI18N
        jLabel17.setText("Funcion:");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 93, -1, -1));

        funciontxt.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        funciontxt.setForeground(new java.awt.Color(204, 204, 204));
        funciontxt.setText("Ingrese la funcion");
        funciontxt.setBorder(null);
        funciontxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                funciontxtMouseClicked(evt);
            }
        });
        jPanel1.add(funciontxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(585, 131, -1, -1));

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(585, 154, 173, 16));

        jLabel18.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/costo.png"))); // NOI18N
        jLabel18.setText("Costo:");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 208, -1, -1));

        costotxt.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        costotxt.setForeground(new java.awt.Color(204, 204, 204));
        costotxt.setText("Ingrese el costo");
        costotxt.setBorder(null);
        costotxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                costotxtMouseClicked(evt);
            }
        });
        jPanel1.add(costotxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(588, 252, -1, -1));

        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(588, 275, 170, 10));

        jLabel19.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/unidad.png"))); // NOI18N
        jLabel19.setText("Unidad de Medida:");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 334, -1, -1));

        unidadtxt.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        unidadtxt.setForeground(new java.awt.Color(204, 204, 204));
        unidadtxt.setText("Ingrese la unidad");
        unidadtxt.setBorder(null);
        unidadtxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                unidadtxtMouseClicked(evt);
            }
        });
        jPanel1.add(unidadtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(591, 384, -1, -1));

        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(583, 407, 175, 10));

        btnAgregar.setBackground(new java.awt.Color(84, 33, 89));
        btnAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarMouseClicked(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Agregar Material");

        javax.swing.GroupLayout btnAgregarLayout = new javax.swing.GroupLayout(btnAgregar);
        btnAgregar.setLayout(btnAgregarLayout);
        btnAgregarLayout.setHorizontalGroup(
            btnAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnAgregarLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jLabel20)
                .addGap(19, 19, 19))
        );
        btnAgregarLayout.setVerticalGroup(
            btnAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnAgregarLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel20)
                .addGap(14, 14, 14))
        );

        jPanel1.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(439, 437, -1, -1));

        errorNombre.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        errorNombre.setForeground(new java.awt.Color(255, 255, 255));
        errorNombre.setText("*");
        jPanel1.add(errorNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(267, 131, -1, -1));

        errorColor.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        errorColor.setForeground(new java.awt.Color(255, 255, 255));
        errorColor.setText("*");
        jPanel1.add(errorColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 252, 20, -1));

        errorMedida.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        errorMedida.setForeground(new java.awt.Color(255, 255, 255));
        errorMedida.setText("*");
        jPanel1.add(errorMedida, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 380, 20, -1));

        errorProveedor.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        errorProveedor.setForeground(new java.awt.Color(255, 255, 255));
        errorProveedor.setText("*");
        jPanel1.add(errorProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 380, 20, -1));

        errorFuncion.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        errorFuncion.setForeground(new java.awt.Color(255, 255, 255));
        errorFuncion.setText("*");
        jPanel1.add(errorFuncion, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 130, 20, -1));

        errorCosto.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        errorCosto.setForeground(new java.awt.Color(255, 255, 255));
        errorCosto.setText("*");
        jPanel1.add(errorCosto, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 250, 20, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMaterialesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMaterialesMouseClicked
        if(mat.vertamanomat()!=0||mob.vertamanomob()!=0||mhr.vertamanoher()!=0){
            MaterialesIngeniero ventana = new MaterialesIngeniero(mat,mob,mhr);
            control.activaVentana(ventana, this);
        }
        else{
            MaterialesIngeniero ventana = new MaterialesIngeniero();
            control.activaVentana(ventana, this);
        }
    }//GEN-LAST:event_btnMaterialesMouseClicked

    private void nombretxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nombretxtMouseClicked
        if(nombretxt.getText().equals("Ingrese el nombre")) {
            nombretxt.setText("");
            nombretxt.setForeground(Color.black);
        }
    }//GEN-LAST:event_nombretxtMouseClicked

    private void colortxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_colortxtMouseClicked
        if(colortxt.getText().equals("Ingrese el color")) {
            colortxt.setText("");
            colortxt.setForeground(Color.black);
        }
    }//GEN-LAST:event_colortxtMouseClicked

    private void proveedortxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_proveedortxtMouseClicked
        if(proveedortxt.getText().equals("Ingrese el proveedor")) {
            proveedortxt.setText("");
            proveedortxt.setForeground(Color.black);
        }
    }//GEN-LAST:event_proveedortxtMouseClicked

    private void funciontxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_funciontxtMouseClicked
        if(funciontxt.getText().equals("Ingrese la funcion")) {
            funciontxt.setText("");
            funciontxt.setForeground(Color.black);
        }
    }//GEN-LAST:event_funciontxtMouseClicked

    private void costotxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_costotxtMouseClicked
        if(costotxt.getText().equals("Ingrese el costo")) {
            costotxt.setText("");
            costotxt.setForeground(Color.black);
        }
    }//GEN-LAST:event_costotxtMouseClicked

    private void unidadtxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unidadtxtMouseClicked
        if(unidadtxt.getText().equals("Ingrese la unidad")) {
            unidadtxt.setText("");
            unidadtxt.setForeground(Color.black);
        }
    }//GEN-LAST:event_unidadtxtMouseClicked

    private void btnAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarMouseClicked
        errores.setLength(0);
        errorNombre.setForeground(Color.white);
        errorColor.setForeground(Color.white);
        errorProveedor.setForeground(Color.white);
        errorFuncion.setForeground(Color.white);
        errorMedida.setForeground(Color.white);
        errorCosto.setForeground(Color.white);
       //double costo = validarCosto(costotxt.getText());
       if(validarDato(nombretxt.getText(),"el nombre")){
            errorNombre.setForeground(Color.red);
            errores.append("- Ingrese un nombre valido.\n");
        }
       if(validarDato(colortxt.getText(),"el color")){
            errorColor.setForeground(Color.red);
            errores.append("- Ingrese un color valido.\n");
        }
       if(validarDato(proveedortxt.getText(),"el proveedor")){
            errorProveedor.setForeground(Color.red);
            errores.append("- Ingrese un proveedor valido.\n");
        }
       if(validarDato(funciontxt.getText(),"la funcion")){
            errorFuncion.setForeground(Color.red);
            errores.append("- Ingrese una funcion valida.\n");
        }
        try {
            if(validarDato(costotxt.getText(),"el costo")) {
                errores.append("- Ingrese un costo valido.\n");
                errorCosto.setForeground(Color.red);
            }
            double costo = Double.parseDouble(costotxt.getText());
        } catch (NumberFormatException ex) {
            errores.append("- Ingrese un costo valido.\n");
            errorCosto.setForeground(Color.red);
        }
        if(validarDato(unidadtxt.getText(),"la unidad")){
            errorMedida.setForeground(Color.red);
            errores.append("- Ingrese una unidad valido.\n");
        }
        if (errores.length() > 0) {
            JOptionPane.showMessageDialog(null, errores.toString(), "Errores de Validacion", JOptionPane.ERROR_MESSAGE); 
            
        } else {
        Material ag = new Material(nombretxt.getText(),colortxt.getText(),proveedortxt.getText(),funciontxt.getText(),Double.parseDouble(costotxt.getText()),unidadtxt.getText());
        Iterator<Material> it = mat.getMateriales().iterator();
        boolean continuar = false;
        while (it.hasNext() && continuar == false) {
            Material mat1 = it.next();
            if (mat1.getNombre().equalsIgnoreCase(nombretxt.getText())) {
                JOptionPane.showMessageDialog(null, "El material "+mat1.getNombre()+" ya esta en la lista");
                continuar = true;
            }    
        }
        if (continuar == false)
            mat.agregarMaterial(ag);
        nombretxt.setForeground(Color.LIGHT_GRAY);
        nombretxt.setText("Ingrese el nombre");
        colortxt.setForeground(Color.LIGHT_GRAY);
        colortxt.setText("Ingrese el color");
        proveedortxt.setForeground(Color.LIGHT_GRAY);
        proveedortxt.setText("Ingrese el proveedor");
        funciontxt.setForeground(Color.LIGHT_GRAY);
        funciontxt.setText("Ingrese la funcion");
        costotxt.setForeground(Color.LIGHT_GRAY);
        costotxt.setText("Ingrese el costo");
        unidadtxt.setForeground(Color.LIGHT_GRAY);
        unidadtxt.setText("Ingrese la unidad");
        }
        
    }//GEN-LAST:event_btnAgregarMouseClicked

    private void btnManoDeObraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnManoDeObraMouseClicked
        if(mat.vertamanomat()!=0||mob.vertamanomob()!=0||mhr.vertamanoher()!=0){
            ManoDeObraIngeniero ventana = new ManoDeObraIngeniero(mat,mob,mhr);
            control.activaVentana(ventana, this);
        }
        else{
            ManoDeObraIngeniero ventana = new ManoDeObraIngeniero();
            control.activaVentana(ventana, this);
        }
    }//GEN-LAST:event_btnManoDeObraMouseClicked

    private void btnAgregarManoDeObraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarManoDeObraMouseClicked
        if(mat.vertamanomat()!=0||mob.vertamanomob()!=0||mhr.vertamanoher()!=0){
            AgregarManoDeObra ventana = new AgregarManoDeObra(mat,mob,mhr);
            control.activaVentana(ventana, this);
        }
        else{
            AgregarManoDeObra ventana = new AgregarManoDeObra();
            control.activaVentana(ventana, this);
        }    
    }//GEN-LAST:event_btnAgregarManoDeObraMouseClicked

    private void btnHerramientasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHerramientasMouseClicked
        if(mat.vertamanomat()!=0||mob.vertamanomob()!=0||mhr.vertamanoher()!=0){
            HerramientasIngeniero ventana = new HerramientasIngeniero(mat,mob,mhr);
            control.activaVentana(ventana, this);
        }
        else{
            HerramientasIngeniero ventana = new HerramientasIngeniero();
            control.activaVentana(ventana, this);
        }  
    }//GEN-LAST:event_btnHerramientasMouseClicked

    private void btnAgregarHerramientaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarHerramientaMouseClicked
         if(mat.vertamanomat()!=0||mob.vertamanomob()!=0||mhr.vertamanoher()!=0){
            AgregarHerramienta ventana = new AgregarHerramienta(mat,mob,mhr);
            control.activaVentana(ventana, this);
        }
        else{
            AgregarHerramienta ventana = new AgregarHerramienta();
            control.activaVentana(ventana, this);
        }   
    }//GEN-LAST:event_btnAgregarHerramientaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarMaterial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarMaterial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarMaterial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarMaterial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarMaterial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnAgregar;
    private javax.swing.JPanel btnAgregarHerramienta;
    private javax.swing.JPanel btnAgregarManoDeObra;
    private javax.swing.JPanel btnAgregarMaterial;
    private javax.swing.JPanel btnHerramientas;
    private javax.swing.JPanel btnManoDeObra;
    private javax.swing.JPanel btnMateriales;
    private javax.swing.JTextField colortxt;
    private javax.swing.JTextField costotxt;
    private javax.swing.JLabel errorColor;
    private javax.swing.JLabel errorCosto;
    private javax.swing.JLabel errorFuncion;
    private javax.swing.JLabel errorMedida;
    private javax.swing.JLabel errorNombre;
    private javax.swing.JLabel errorProveedor;
    private javax.swing.JTextField funciontxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTextField nombretxt;
    private javax.swing.JTextField proveedortxt;
    private javax.swing.JTextField unidadtxt;
    // End of variables declaration//GEN-END:variables
}
