/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;
import Controller.Controladora;
import Modelo.Apoyo;
import Modelo.ListaHerramientas;
import Modelo.ListaManoDeObra;
import Modelo.ListaMateriales;
import Modelo.Material;
import java.awt.Color;
import java.util.Iterator;
import javax.swing.JOptionPane;

import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;
import org.json.simple.parser.ParseException;

/**
 *
 * @author laura
 */
public class AgregarManoDeObra extends javax.swing.JFrame {

    Controladora control = new Controladora(this);
    ListaMateriales mat = new ListaMateriales();
    ListaHerramientas mhr = new ListaHerramientas();
    ListaManoDeObra mob = new ListaManoDeObra();
    StringBuilder errores = new StringBuilder();
    
    public boolean validarDato(String dato, String mensaje) {
        boolean error = false;
        if (dato == null || dato.isEmpty() || dato.equals("Ingrese "+mensaje)){
            error = true;
        }
        return error;
    }
    
    
    public AgregarManoDeObra() {
        initComponents();
        mat.agregarMaterial();
        mob.agregarManoDeObra();
        mhr.agregarHerramienta();
        control.iniciaVentana(this);
    }
    
    public AgregarManoDeObra(ListaMateriales mati, ListaManoDeObra mo, ListaHerramientas mh) {
        if(mati.vertamanomat()==0){
            mati.agregarMaterial();
        }
        if(mo.vertamanomob()==0){
            mo.agregarManoDeObra();
        }
        if(mh.vertamanoher()==0){
            mh.agregarHerramienta();
        }
        mat=mati;
        mob=mo;
        mhr=mh;
        initComponents();
        control.iniciaVentana(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        nombretxt = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel31 = new javax.swing.JLabel();
        costotxt = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel32 = new javax.swing.JLabel();
        unidadtxt = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        btnAgregar = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        errorNombre = new javax.swing.JLabel();
        errorCosto = new javax.swing.JLabel();
        errorMedida = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        btnAggMaterial = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        btnMateriales = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        btnHerramientas = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        btnAgregarHerramienta = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        btnManoDeObra = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        btnAggManoDeObra = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel27.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/mano de obra2.png"))); // NOI18N
        jLabel27.setText("Nombre del Trabajador:");

        nombretxt.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        nombretxt.setForeground(new java.awt.Color(204, 204, 204));
        nombretxt.setText("Ingrese el trabajador");
        nombretxt.setBorder(null);
        nombretxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nombretxtMouseClicked(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        jLabel31.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/costo.png"))); // NOI18N
        jLabel31.setText("Costo:");

        costotxt.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        costotxt.setForeground(new java.awt.Color(204, 204, 204));
        costotxt.setText("Ingrese el costo");
        costotxt.setBorder(null);
        costotxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                costotxtMouseClicked(evt);
            }
        });

        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));

        jLabel32.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cobra por.png"))); // NOI18N
        jLabel32.setText("Cobra por:");

        unidadtxt.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        unidadtxt.setForeground(new java.awt.Color(204, 204, 204));
        unidadtxt.setText("Ingrese la unidad");
        unidadtxt.setBorder(null);
        unidadtxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                unidadtxtMouseClicked(evt);
            }
        });

        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));

        btnAgregar.setBackground(new java.awt.Color(84, 33, 89));
        btnAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarMouseClicked(evt);
            }
        });

        jLabel33.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("Agregar Mano de Obra");

        javax.swing.GroupLayout btnAgregarLayout = new javax.swing.GroupLayout(btnAgregar);
        btnAgregar.setLayout(btnAgregarLayout);
        btnAgregarLayout.setHorizontalGroup(
            btnAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnAgregarLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLabel33)
                .addGap(15, 15, 15))
        );
        btnAgregarLayout.setVerticalGroup(
            btnAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAgregarLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel33)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        errorNombre.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        errorNombre.setForeground(new java.awt.Color(255, 255, 255));
        errorNombre.setText("*");

        errorCosto.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        errorCosto.setForeground(new java.awt.Color(255, 255, 255));
        errorCosto.setText("*");

        errorMedida.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        errorMedida.setForeground(new java.awt.Color(255, 255, 255));
        errorMedida.setText("*");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel27)
                    .addComponent(jLabel31)
                    .addComponent(jLabel32)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(errorNombre)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(errorCosto, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(errorMedida, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombretxt, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(costotxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(unidadtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jSeparator6, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(150, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombretxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(errorNombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jLabel31)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(costotxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(errorCosto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(jLabel32)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(unidadtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(errorMedida))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );

        jPanel4.setBackground(new java.awt.Color(84, 33, 89));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo.png"))); // NOI18N

        btnAggMaterial.setBackground(new java.awt.Color(83, 43, 100));
        btnAggMaterial.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAggMaterial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAggMaterialMouseClicked(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Agregar Material.png"))); // NOI18N

        jLabel16.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Agregar Material");

        javax.swing.GroupLayout btnAggMaterialLayout = new javax.swing.GroupLayout(btnAggMaterial);
        btnAggMaterial.setLayout(btnAggMaterialLayout);
        btnAggMaterialLayout.setHorizontalGroup(
            btnAggMaterialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAggMaterialLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnAggMaterialLayout.setVerticalGroup(
            btnAggMaterialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAggMaterialLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(btnAggMaterialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel16)
                    .addComponent(jLabel15))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        btnMateriales.setBackground(new java.awt.Color(83, 43, 100));
        btnMateriales.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMateriales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMaterialesMouseClicked(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/materiales.png"))); // NOI18N

        jLabel18.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Materiales");

        javax.swing.GroupLayout btnMaterialesLayout = new javax.swing.GroupLayout(btnMateriales);
        btnMateriales.setLayout(btnMaterialesLayout);
        btnMaterialesLayout.setHorizontalGroup(
            btnMaterialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnMaterialesLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addComponent(jLabel18)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnMaterialesLayout.setVerticalGroup(
            btnMaterialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnMaterialesLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(btnMaterialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel18)
                    .addComponent(jLabel17))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        btnHerramientas.setBackground(new java.awt.Color(83, 43, 100));
        btnHerramientas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHerramientas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHerramientasMouseClicked(evt);
            }
        });

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/herramientas.png"))); // NOI18N

        jLabel20.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Herramientas");

        javax.swing.GroupLayout btnHerramientasLayout = new javax.swing.GroupLayout(btnHerramientas);
        btnHerramientas.setLayout(btnHerramientasLayout);
        btnHerramientasLayout.setHorizontalGroup(
            btnHerramientasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnHerramientasLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel20)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnHerramientasLayout.setVerticalGroup(
            btnHerramientasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnHerramientasLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(btnHerramientasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel20)
                    .addComponent(jLabel19))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        btnAgregarHerramienta.setBackground(new java.awt.Color(83, 43, 100));
        btnAgregarHerramienta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregarHerramienta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarHerramientaMouseClicked(evt);
            }
        });

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/herramienta (2).png"))); // NOI18N

        jLabel22.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Agregar Herramienta");

        javax.swing.GroupLayout btnAgregarHerramientaLayout = new javax.swing.GroupLayout(btnAgregarHerramienta);
        btnAgregarHerramienta.setLayout(btnAgregarHerramientaLayout);
        btnAgregarHerramientaLayout.setHorizontalGroup(
            btnAgregarHerramientaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAgregarHerramientaLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel22)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnAgregarHerramientaLayout.setVerticalGroup(
            btnAgregarHerramientaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAgregarHerramientaLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(btnAgregarHerramientaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel22)
                    .addComponent(jLabel21))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        btnManoDeObra.setBackground(new java.awt.Color(83, 43, 100));
        btnManoDeObra.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnManoDeObra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnManoDeObraMouseClicked(evt);
            }
        });

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/mano de obra.png"))); // NOI18N

        jLabel24.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Mano de Obra");

        javax.swing.GroupLayout btnManoDeObraLayout = new javax.swing.GroupLayout(btnManoDeObra);
        btnManoDeObra.setLayout(btnManoDeObraLayout);
        btnManoDeObraLayout.setHorizontalGroup(
            btnManoDeObraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnManoDeObraLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel24)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnManoDeObraLayout.setVerticalGroup(
            btnManoDeObraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnManoDeObraLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(btnManoDeObraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel24)
                    .addComponent(jLabel23))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        btnAggManoDeObra.setBackground(new java.awt.Color(85, 55, 118));
        btnAggManoDeObra.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/modificar MO.png"))); // NOI18N

        jLabel26.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Agregar Mano de Obra");

        javax.swing.GroupLayout btnAggManoDeObraLayout = new javax.swing.GroupLayout(btnAggManoDeObra);
        btnAggManoDeObra.setLayout(btnAggManoDeObraLayout);
        btnAggManoDeObraLayout.setHorizontalGroup(
            btnAggManoDeObraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAggManoDeObraLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel26)
                .addContainerGap(43, Short.MAX_VALUE))
        );
        btnAggManoDeObraLayout.setVerticalGroup(
            btnAggManoDeObraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAggManoDeObraLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(btnAggManoDeObraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel26)
                    .addComponent(jLabel25))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnMateriales, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnAggMaterial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnHerramientas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnAgregarHerramienta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnManoDeObra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel14)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(btnAggManoDeObra, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMateriales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAggMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnHerramientas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAgregarHerramienta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnManoDeObra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAggManoDeObra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    //BORRAAAAAAAAAAAR BOTON!!!!!!!!!!!!!!!!!!!!!!
    private void btnMaterialesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMaterialesMouseClicked
        if(mat.vertamanomat()!=0||mob.vertamanomob()!=0||mhr.vertamanoher()!=0){
            MaterialesIngeniero ventana = new MaterialesIngeniero(mat,mob,mhr);
            control.activaVentana(ventana, this);
        }
        else{
            MaterialesIngeniero ventana = new MaterialesIngeniero();
            control.activaVentana(ventana, this);
        }
    }//GEN-LAST:event_btnMaterialesMouseClicked

    //BORRAR BOTON TAMBIEN ACA
    private void btnManoDeObraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnManoDeObraMouseClicked
        if(mat.vertamanomat()!=0||mob.vertamanomob()!=0||mhr.vertamanoher()!=0){
            ManoDeObraIngeniero ventana = new ManoDeObraIngeniero(mat,mob,mhr);
            control.activaVentana(ventana, this);
        }
        else{
            ManoDeObraIngeniero ventana = new ManoDeObraIngeniero();
            control.activaVentana(ventana, this);
        }
    }//GEN-LAST:event_btnManoDeObraMouseClicked

    private void nombretxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nombretxtMouseClicked
        if(nombretxt.getText().equals("Ingrese el trabajador")) {
            nombretxt.setText("");
            nombretxt.setForeground(Color.black);
        }
    }//GEN-LAST:event_nombretxtMouseClicked

    private void costotxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_costotxtMouseClicked
        if(costotxt.getText().equals("Ingrese el costo")) {
            costotxt.setText("");
            costotxt.setForeground(Color.black);
        }
    }//GEN-LAST:event_costotxtMouseClicked

    private void unidadtxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unidadtxtMouseClicked
        if(unidadtxt.getText().equals("Ingrese la unidad")) {
            unidadtxt.setText("");
            unidadtxt.setForeground(Color.black);
        }
    }//GEN-LAST:event_unidadtxtMouseClicked

    private void btnAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarMouseClicked
        errores.setLength(0);
        errorNombre.setForeground(Color.white);
        errorMedida.setForeground(Color.white);
        errorCosto.setForeground(Color.white);
       if(validarDato(nombretxt.getText(),"el trabajador")){
            errorNombre.setForeground(Color.red);
            errores.append("- Ingrese un nombre valido.\n");
        }
        try {
            if(validarDato(costotxt.getText(),"el costo")) {
                errores.append("- Ingrese un costo valido.\n");
                errorCosto.setForeground(Color.red);
            }
            double costo = Double.parseDouble(costotxt.getText());
        } catch (NumberFormatException ex) {
            errores.append("- Ingrese un costo valido.\n");
            errorCosto.setForeground(Color.red);
        }
        if(validarDato(unidadtxt.getText(),"la unidad")){
            errorMedida.setForeground(Color.red);
            errores.append("- Ingrese una unidad valido.\n");
        }
        if (errores.length() > 0) {
            JOptionPane.showMessageDialog(null, errores.toString(), "Errores de Validacion", JOptionPane.ERROR_MESSAGE); 
            
        } else {
        Apoyo ag = new Apoyo(nombretxt.getText(),Double.parseDouble(costotxt.getText()),unidadtxt.getText());
        Iterator<Apoyo> it = mob.getManoDeObra().iterator();
        boolean continuar = false;
        while (it.hasNext() && continuar == false) {
            Apoyo mo = it.next();
            if (mo.getNombre().equalsIgnoreCase(nombretxt.getText())) {
                JOptionPane.showMessageDialog(null, "La mano de obra "+mo.getNombre()+" ya esta en la lista");
                continuar = true;
            }    
        }
        if (continuar == false)
            mob.agregarManoDeObraI(ag);
        nombretxt.setForeground(Color.LIGHT_GRAY);
        nombretxt.setText("Ingrese el nombre");
        costotxt.setForeground(Color.LIGHT_GRAY);
        costotxt.setText("Ingrese el costo");
        unidadtxt.setForeground(Color.LIGHT_GRAY);
        unidadtxt.setText("Ingrese la unidad");
        }

    }//GEN-LAST:event_btnAgregarMouseClicked

    //BORRAME!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    private void btnAggMaterialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAggMaterialMouseClicked
        // TODO add your handling code here:
        if(mat.vertamanomat()!=0||mob.vertamanomob()!=0||mhr.vertamanoher()!=0){
            AgregarMaterial ventana = new AgregarMaterial(mat,mob,mhr);
            control.activaVentana(ventana, this);
        }
        else{
            AgregarMaterial ventana = new AgregarMaterial();
            control.activaVentana(ventana, this);
        }
    }//GEN-LAST:event_btnAggMaterialMouseClicked

    private void btnHerramientasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHerramientasMouseClicked
        // TODO add your handling code here:
        if(mat.vertamanomat()!=0||mob.vertamanomob()!=0||mhr.vertamanoher()!=0){
            HerramientasIngeniero ventana = new HerramientasIngeniero(mat,mob,mhr);
            control.activaVentana(ventana, this);
        }
        else{
            HerramientasIngeniero ventana = new HerramientasIngeniero();
            control.activaVentana(ventana, this);
        } 
    }//GEN-LAST:event_btnHerramientasMouseClicked

    private void btnAgregarHerramientaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarHerramientaMouseClicked
        // TODO add your handling code here:
        if(mat.vertamanomat()!=0||mob.vertamanomob()!=0||mhr.vertamanoher()!=0){
            AgregarHerramienta ventana = new AgregarHerramienta(mat,mob,mhr);
            control.activaVentana(ventana, this);
        }
        else{
            AgregarHerramienta ventana = new AgregarHerramienta();
            control.activaVentana(ventana, this);
        }   
    }//GEN-LAST:event_btnAgregarHerramientaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarManoDeObra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarManoDeObra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarManoDeObra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarManoDeObra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarManoDeObra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnAggManoDeObra;
    private javax.swing.JPanel btnAggMaterial;
    private javax.swing.JPanel btnAgregar;
    private javax.swing.JPanel btnAgregarHerramienta;
    private javax.swing.JPanel btnHerramientas;
    private javax.swing.JPanel btnManoDeObra;
    private javax.swing.JPanel btnMateriales;
    private javax.swing.JTextField costotxt;
    private javax.swing.JLabel errorCosto;
    private javax.swing.JLabel errorMedida;
    private javax.swing.JLabel errorNombre;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTextField nombretxt;
    private javax.swing.JTextField unidadtxt;
    // End of variables declaration//GEN-END:variables
}
