/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;
import Modelo.Material;
import Modelo.Apoyo;
import Modelo.ListaMateriales;
import Modelo.PresupuestoMateriales;
import Modelo.ListaPresupuestoM;
import Modelo.ListaManoDeObra;
import Controller.Controladora;
import Modelo.ListaHerramientas;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JOptionPane;

import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;
import org.json.simple.parser.ParseException;

/**
 *
 * @author laura
 */
public class VentanaPresupuesto extends javax.swing.JFrame {

    Controladora control = new Controladora(this);
    ListaPresupuestoM preM = new ListaPresupuestoM(); 
    ListaManoDeObra mob = new ListaManoDeObra();
    ListaHerramientas her = new ListaHerramientas();
    ArrayList<PresupuestoMateriales> listaM = new ArrayList<>(); 
    ArrayList<Apoyo> listaMO = new ArrayList<>();
    ArrayList<Apoyo> listaHr = new ArrayList<>();
    
    
    public VentanaPresupuesto() {
        initComponents();
        control.llenarTablaMaterialesP(tablaPresupuestoMat, listaM);
        control.llenarTablaManoDeObra(tablaPresupuestoMO, listaMO);
        control.llenarHerramientas(tablaPresupuestoH, listaHr);
        control.iniciaVentana(this);
    }
    public VentanaPresupuesto(ArrayList<PresupuestoMateriales> listaPresupuestoM, ArrayList<Apoyo> listaPresupuestoMO, ArrayList<Apoyo> listaPresupuestoH) {
        listaM=listaPresupuestoM;
        listaMO = listaPresupuestoMO;
        listaHr = listaPresupuestoH;
        initComponents();
        control.llenarTablaMaterialesP(tablaPresupuestoMat, listaPresupuestoM);
        totalM.setText(Double.toString(control.getTotalM())+"$");
        control.llenarTablaManoDeObra(tablaPresupuestoMO, listaPresupuestoMO);
        totalMO.setText(Double.toString(control.getTotalMO())+"$");
        control.llenarHerramientas(tablaPresupuestoH, listaPresupuestoH);
        totalH.setText(Double.toString(control.getTotalH())+"$");
        presupuestoTotal.setText(Double.toString(control.getTotalM()+control.getTotalMO()+control.getTotalH())+"$");
        control.iniciaVentana(this);
    }
    
    public void eliminarMaterial(PresupuestoMateriales material) {
        listaM.remove(material);
    }
    
    public void eliminarManoDeObra(Apoyo mano) {
        listaMO.remove(mano);
    }
    
    public void eliminarHerramienta(Apoyo her) {
        listaHr.remove(her);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnMateriales = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnHerramientas = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnManoDeObra = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnPresupuesto = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPresupuestoMat = new javax.swing.JTable();
        jLabel19 = new javax.swing.JLabel();
        totalM = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaPresupuestoMO = new javax.swing.JTable();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        totalMO = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaPresupuestoH = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        totalH = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        presupuestoTotal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(84, 33, 89));

        btnMateriales.setBackground(new java.awt.Color(83, 43, 100));
        btnMateriales.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMateriales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMaterialesMouseClicked(evt);
            }
        });
        btnMateriales.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                btnMaterialesComponentResized(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/materiales.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Materiales");

        javax.swing.GroupLayout btnMaterialesLayout = new javax.swing.GroupLayout(btnMateriales);
        btnMateriales.setLayout(btnMaterialesLayout);
        btnMaterialesLayout.setHorizontalGroup(
            btnMaterialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnMaterialesLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnMaterialesLayout.setVerticalGroup(
            btnMaterialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnMaterialesLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(btnMaterialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        btnHerramientas.setBackground(new java.awt.Color(83, 43, 100));
        btnHerramientas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHerramientas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHerramientasMouseClicked(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/herramientas.png"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Herramientas");

        javax.swing.GroupLayout btnHerramientasLayout = new javax.swing.GroupLayout(btnHerramientas);
        btnHerramientas.setLayout(btnHerramientasLayout);
        btnHerramientasLayout.setHorizontalGroup(
            btnHerramientasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnHerramientasLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnHerramientasLayout.setVerticalGroup(
            btnHerramientasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnHerramientasLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(btnHerramientasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        btnManoDeObra.setBackground(new java.awt.Color(83, 43, 100));
        btnManoDeObra.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnManoDeObra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnManoDeObraMouseClicked(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/mano de obra.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Mano de Obra");

        javax.swing.GroupLayout btnManoDeObraLayout = new javax.swing.GroupLayout(btnManoDeObra);
        btnManoDeObra.setLayout(btnManoDeObraLayout);
        btnManoDeObraLayout.setHorizontalGroup(
            btnManoDeObraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnManoDeObraLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnManoDeObraLayout.setVerticalGroup(
            btnManoDeObraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnManoDeObraLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(btnManoDeObraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        btnPresupuesto.setBackground(new java.awt.Color(85, 55, 118));
        btnPresupuesto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/presupuesto.png"))); // NOI18N

        jLabel15.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Ver Presupuesto");

        javax.swing.GroupLayout btnPresupuestoLayout = new javax.swing.GroupLayout(btnPresupuesto);
        btnPresupuesto.setLayout(btnPresupuestoLayout);
        btnPresupuestoLayout.setHorizontalGroup(
            btnPresupuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPresupuestoLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel15)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnPresupuestoLayout.setVerticalGroup(
            btnPresupuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPresupuestoLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(btnPresupuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnMateriales, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnManoDeObra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnPresupuesto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel17)
                .addContainerGap(64, Short.MAX_VALUE))
            .addComponent(btnHerramientas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMateriales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnManoDeObra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnHerramientas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPresupuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bg.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 620));

        jLabel7.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/material3.png"))); // NOI18N
        jLabel7.setText("Materiales Presupuestados:");
        bg.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 6, -1, -1));

        tablaPresupuestoMat.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        tablaPresupuestoMat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Material", "Color", "Proveedor", "Funcion", "Costo ($)", "Unidad", "Cantidad", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tablaPresupuestoMat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tablaPresupuestoMat.setGridColor(new java.awt.Color(255, 255, 255));
        tablaPresupuestoMat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaPresupuestoMatMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaPresupuestoMat);

        bg.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 42, 500, 97));

        jLabel19.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/totalm.png"))); // NOI18N
        jLabel19.setText("Total materiales presupuestados:");
        bg.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 145, -1, -1));

        totalM.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        totalM.setText("0.00$");
        bg.add(totalM, new org.netbeans.lib.awtextra.AbsoluteConstraints(516, 152, -1, -1));

        tablaPresupuestoMO.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        tablaPresupuestoMO.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Trabajador", "Costo ($)", "Cobra por"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tablaPresupuestoMO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaPresupuestoMOMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablaPresupuestoMO);

        bg.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 233, 467, 81));

        jLabel20.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/mano de obra2.png"))); // NOI18N
        jLabel20.setText("Mano de Obra Presupuestada:");
        bg.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 195, -1, -1));

        jLabel21.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/totalm.png"))); // NOI18N
        jLabel21.setText("Total mano de obra presupuestada:");
        bg.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 320, -1, -1));

        totalMO.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        totalMO.setText("0.00$");
        bg.add(totalMO, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 327, -1, -1));

        jLabel8.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/herramienta.png"))); // NOI18N
        jLabel8.setText("Herramientas Presupuestadas:");
        bg.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 376, -1, -1));

        tablaPresupuestoH.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        tablaPresupuestoH.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Herramienta", "Costo ($)", "Cobra por"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tablaPresupuestoH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaPresupuestoHMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tablaPresupuestoH);

        bg.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 414, -1, 95));

        jLabel9.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/totalm.png"))); // NOI18N
        jLabel9.setText("Total herramientas presupuestadas:");
        bg.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 515, -1, -1));

        totalH.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        totalH.setText("0.00$");
        bg.add(totalH, new org.netbeans.lib.awtextra.AbsoluteConstraints(532, 522, -1, -1));

        jLabel10.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/total.png"))); // NOI18N
        jLabel10.setText("Presupuesto Total:");
        bg.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 559, -1, -1));

        presupuestoTotal.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        presupuestoTotal.setText("0.00$");
        bg.add(presupuestoTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(472, 563, -1, -1));

        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMaterialesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMaterialesMouseClicked

        if (listaM.size() != 0 || listaMO.size() != 0 || listaHr.size()!=0){
            VentanaMateriales ventana = new VentanaMateriales(listaM, listaMO, listaHr);
            control.activaVentana(ventana, this);
        }
        else{
        VentanaMateriales ventana = new VentanaMateriales();
        control.activaVentana(ventana, this);
        }
    }//GEN-LAST:event_btnMaterialesMouseClicked

    private void btnMaterialesComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_btnMaterialesComponentResized
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMaterialesComponentResized

    private void btnHerramientasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHerramientasMouseClicked
        if (listaM.size() != 0 || listaMO.size() != 0 || listaHr.size()!=0){
            VentanaHerramientas ventana = new VentanaHerramientas(listaM, listaMO, listaHr);
            control.activaVentana(ventana, this);
        }
        else{
        VentanaHerramientas ventana = new VentanaHerramientas();
        control.activaVentana(ventana, this);
        }
    }//GEN-LAST:event_btnHerramientasMouseClicked

    private void btnManoDeObraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnManoDeObraMouseClicked
        if (listaM.size() != 0 || listaMO.size() != 0 || listaHr.size()!=0){
            VentanaManoDeObra ventana = new VentanaManoDeObra(listaM, listaMO, listaHr);
            control.activaVentana(ventana, this);
        }
        else{
        VentanaManoDeObra ventana = new VentanaManoDeObra();
        control.activaVentana(ventana, this);
        }
    }//GEN-LAST:event_btnManoDeObraMouseClicked

    private void tablaPresupuestoMatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaPresupuestoMatMouseClicked
        int row = tablaPresupuestoMat.rowAtPoint(evt.getPoint());
        if(row>=0){
            String material = (String)tablaPresupuestoMat.getValueAt(row, 0);
            String color = (String)tablaPresupuestoMat.getValueAt(row, 1);
            String proveedor = (String)tablaPresupuestoMat.getValueAt(row, 2);
            String funcion = (String)tablaPresupuestoMat.getValueAt(row, 3);
            double costo = Double.parseDouble(tablaPresupuestoMat.getValueAt(row, 4).toString());
            String unidad = (String)tablaPresupuestoMat.getValueAt(row, 5);
            int cant = Integer.parseInt(tablaPresupuestoMat.getValueAt(row, 6).toString());
            double total = Double.parseDouble(tablaPresupuestoMat.getValueAt(row, 7).toString());
            String mensaje = "Material: "+material+" \n"+
                             "Color: "+color+" \n"+
                             "Proveedor: "+proveedor+" \n"+
                             "Funcion: "+funcion+" \n"+
                             "Costo: "+costo+"$"+" \n"+
                             "Cantidad: "+cant+" \n"+
                             "Total: "+total+"$"+" \n"+
                             "Unidad: "+unidad;
            String[] opciones = {"Volver","Eliminar del presupuesto"};
            int opc = JOptionPane.showOptionDialog(null, mensaje, "Detalles del Material", JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE, null, opciones, opciones[1]);
            switch(opc) {
                case 1: preM.setPresupuestoMateriales(listaM);
                        Iterator<PresupuestoMateriales> it = listaM.iterator();
                        PresupuestoMateriales eliminar = new PresupuestoMateriales();
                        while (it.hasNext()) {
                            PresupuestoMateriales mate = it.next();
                            if (mate.getNombre() == material) {
                                eliminar = mate;
                            }
                        }
                        eliminarMaterial(eliminar);
                        listaM = preM.getPresupuestoMateriales();
                        VentanaPresupuesto ventana = new VentanaPresupuesto(listaM,listaMO,listaHr);
                        control.activaVentana(ventana, this);
                        break;
            }
        }
    }//GEN-LAST:event_tablaPresupuestoMatMouseClicked

    private void tablaPresupuestoMOMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaPresupuestoMOMouseClicked
       int row = tablaPresupuestoMO.rowAtPoint(evt.getPoint());
        if(row>=0){
            String mo = (String)tablaPresupuestoMO.getValueAt(row, 0);
            double costo = Double.parseDouble(tablaPresupuestoMO.getValueAt(row, 1).toString());
            String unidad = (String)tablaPresupuestoMO.getValueAt(row, 2);
            String mensaje = "Mano de Obra: "+mo+" \n"+
                             "Costo: "+costo+"$"+" \n"+
                             "Cobra por: "+unidad;
            String[] opciones = {"Volver","Eliminar del presupuesto"};
            int opc = JOptionPane.showOptionDialog(null, mensaje, "Detalles de Mano de Obra", JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE, null, opciones, opciones[1]);
            switch(opc) {
                case 1: mob.setManoDeObra(listaMO);
                        Iterator<Apoyo> it = listaMO.iterator();
                        Apoyo eliminar = new Apoyo();
                        while (it.hasNext()) {
                            Apoyo m = it.next();
                            if (m.getNombre() == mo) {
                                eliminar = m;
                            }
                        }
                        eliminarManoDeObra(eliminar);
                        listaMO = mob.getManoDeObra();
                        VentanaPresupuesto ventana = new VentanaPresupuesto(listaM,listaMO,listaHr);
                        control.activaVentana(ventana, this);
                        break;
            }
        }
    }//GEN-LAST:event_tablaPresupuestoMOMouseClicked

    private void tablaPresupuestoHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaPresupuestoHMouseClicked
        int row = tablaPresupuestoH.rowAtPoint(evt.getPoint());
        if(row>=0){
            String h = (String)tablaPresupuestoH.getValueAt(row, 0);
            double costo = Double.parseDouble(tablaPresupuestoH.getValueAt(row, 1).toString());
            String unidad = (String)tablaPresupuestoH.getValueAt(row, 2);
            String mensaje = "Herramienta: "+h+" \n"+
                             "Costo: "+costo+"$"+" \n"+
                             "Cobra por: "+unidad;
            String[] opciones = {"Volver","Eliminar del presupuesto"};
            int opc = JOptionPane.showOptionDialog(null, mensaje, "Detalles de la Herramienta", JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE, null, opciones, opciones[1]);
            switch(opc) {
                case 1: her.setHerramientas(listaHr);
                        Iterator<Apoyo> it = listaHr.iterator();
                        Apoyo eliminar = new Apoyo();
                        while (it.hasNext()) {
                            Apoyo m = it.next();
                            if (m.getNombre() == h) {
                                eliminar = m;
                            }
                        }
                        eliminarHerramienta(eliminar);
                        listaHr = her.getHerramientas();
                        VentanaPresupuesto ventana = new VentanaPresupuesto(listaM,listaMO,listaHr);
                        control.activaVentana(ventana, this);
                        break;
            }
        }
    }//GEN-LAST:event_tablaPresupuestoHMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPresupuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPresupuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPresupuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPresupuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPresupuesto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JPanel btnHerramientas;
    private javax.swing.JPanel btnManoDeObra;
    private javax.swing.JPanel btnMateriales;
    private javax.swing.JPanel btnPresupuesto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel presupuestoTotal;
    private javax.swing.JTable tablaPresupuestoH;
    private javax.swing.JTable tablaPresupuestoMO;
    private javax.swing.JTable tablaPresupuestoMat;
    private javax.swing.JLabel totalH;
    private javax.swing.JLabel totalM;
    private javax.swing.JLabel totalMO;
    // End of variables declaration//GEN-END:variables
}
