/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;
import Controller.Controladora;
import Modelo.ListaHerramientas;
import Modelo.ListaManoDeObra;
import Modelo.ListaMateriales;

import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;
import org.json.simple.parser.ParseException;
/**
 *
 * @author laura
 */
public class VentanaIngeniero extends javax.swing.JFrame {
    
    Controladora control;
    ListaMateriales mat = new ListaMateriales();
    ListaManoDeObra mob = new ListaManoDeObra();
    ListaHerramientas mhr = new ListaHerramientas();
    
    public VentanaIngeniero() {
        initComponents();
        control = new Controladora(this);
        control.iniciaVentana(this);
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnMateriales = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnAgregarMaterial = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnHerramientas = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnAgregarHerramienta = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnManoDeObra = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnAgregarManoDeObra = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(84, 33, 89));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 6, -1, 105));

        btnMateriales.setBackground(new java.awt.Color(83, 43, 100));
        btnMateriales.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMateriales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMaterialesMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Agregar Material.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Agregar Material");

        javax.swing.GroupLayout btnMaterialesLayout = new javax.swing.GroupLayout(btnMateriales);
        btnMateriales.setLayout(btnMaterialesLayout);
        btnMaterialesLayout.setHorizontalGroup(
            btnMaterialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnMaterialesLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnMaterialesLayout.setVerticalGroup(
            btnMaterialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnMaterialesLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(btnMaterialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel2.add(btnMateriales, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 183, 239, -1));

        btnAgregarMaterial.setBackground(new java.awt.Color(83, 43, 100));
        btnAgregarMaterial.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregarMaterial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarMaterialMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/materiales.png"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Materiales");

        javax.swing.GroupLayout btnAgregarMaterialLayout = new javax.swing.GroupLayout(btnAgregarMaterial);
        btnAgregarMaterial.setLayout(btnAgregarMaterialLayout);
        btnAgregarMaterialLayout.setHorizontalGroup(
            btnAgregarMaterialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAgregarMaterialLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnAgregarMaterialLayout.setVerticalGroup(
            btnAgregarMaterialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAgregarMaterialLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(btnAgregarMaterialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel2.add(btnAgregarMaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 117, 239, -1));

        btnHerramientas.setBackground(new java.awt.Color(83, 43, 100));
        btnHerramientas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHerramientas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHerramientasMouseClicked(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/herramientas.png"))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Herramientas");

        javax.swing.GroupLayout btnHerramientasLayout = new javax.swing.GroupLayout(btnHerramientas);
        btnHerramientas.setLayout(btnHerramientasLayout);
        btnHerramientasLayout.setHorizontalGroup(
            btnHerramientasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnHerramientasLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnHerramientasLayout.setVerticalGroup(
            btnHerramientasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnHerramientasLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(btnHerramientasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel2.add(btnHerramientas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 249, 239, -1));

        btnAgregarHerramienta.setBackground(new java.awt.Color(83, 43, 100));
        btnAgregarHerramienta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregarHerramienta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarHerramientaMouseClicked(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/herramienta (2).png"))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Agregar Herramienta");

        javax.swing.GroupLayout btnAgregarHerramientaLayout = new javax.swing.GroupLayout(btnAgregarHerramienta);
        btnAgregarHerramienta.setLayout(btnAgregarHerramientaLayout);
        btnAgregarHerramientaLayout.setHorizontalGroup(
            btnAgregarHerramientaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAgregarHerramientaLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnAgregarHerramientaLayout.setVerticalGroup(
            btnAgregarHerramientaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAgregarHerramientaLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(btnAgregarHerramientaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel2.add(btnAgregarHerramienta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 315, 239, -1));

        btnManoDeObra.setBackground(new java.awt.Color(83, 43, 100));
        btnManoDeObra.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnManoDeObra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnManoDeObraMouseClicked(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/mano de obra.png"))); // NOI18N

        jLabel11.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Mano de Obra");

        javax.swing.GroupLayout btnManoDeObraLayout = new javax.swing.GroupLayout(btnManoDeObra);
        btnManoDeObra.setLayout(btnManoDeObraLayout);
        btnManoDeObraLayout.setHorizontalGroup(
            btnManoDeObraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnManoDeObraLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnManoDeObraLayout.setVerticalGroup(
            btnManoDeObraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnManoDeObraLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(btnManoDeObraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel2.add(btnManoDeObra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 381, 239, -1));

        btnAgregarManoDeObra.setBackground(new java.awt.Color(83, 43, 100));
        btnAgregarManoDeObra.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregarManoDeObra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarManoDeObraMouseClicked(evt);
            }
        });

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/modificar MO.png"))); // NOI18N

        jLabel13.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Agregar Mano de Obra");

        javax.swing.GroupLayout btnAgregarManoDeObraLayout = new javax.swing.GroupLayout(btnAgregarManoDeObra);
        btnAgregarManoDeObra.setLayout(btnAgregarManoDeObraLayout);
        btnAgregarManoDeObraLayout.setHorizontalGroup(
            btnAgregarManoDeObraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAgregarManoDeObraLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addContainerGap(43, Short.MAX_VALUE))
        );
        btnAgregarManoDeObraLayout.setVerticalGroup(
            btnAgregarManoDeObraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAgregarManoDeObraLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(btnAgregarManoDeObraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel2.add(btnAgregarManoDeObra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 447, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel14.setFont(new java.awt.Font("Roboto", 1, 48)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(84, 33, 89));
        jLabel14.setText("¡Bienvenido, Ingeniero!");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 106, -1, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ingeniero.png"))); // NOI18N
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(483, 203, 108, 110));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarMaterialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarMaterialMouseClicked
        if(mat.vertamanomat()!=0||mob.vertamanomob()!=0||mhr.vertamanoher()!=0){
            MaterialesIngeniero ventana = new MaterialesIngeniero(mat,mob,mhr);
            control.activaVentana(ventana, this);
        }
        else{
            MaterialesIngeniero ventana = new MaterialesIngeniero();
            control.activaVentana(ventana, this);
        }
    }//GEN-LAST:event_btnAgregarMaterialMouseClicked

    private void btnMaterialesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMaterialesMouseClicked
        if(mat.vertamanomat()!=0||mob.vertamanomob()!=0||mhr.vertamanoher()!=0){
            AgregarMaterial ventana = new AgregarMaterial(mat,mob,mhr);
            control.activaVentana(ventana, this);
        }
        else{
            AgregarMaterial ventana = new AgregarMaterial();
            control.activaVentana(ventana, this);
        }
    }//GEN-LAST:event_btnMaterialesMouseClicked

    private void btnManoDeObraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnManoDeObraMouseClicked
        if(mat.vertamanomat()!=0||mob.vertamanomob()!=0||mhr.vertamanoher()!=0){
            ManoDeObraIngeniero ventana = new ManoDeObraIngeniero(mat,mob,mhr);
            control.activaVentana(ventana, this);
        }
        else{
            ManoDeObraIngeniero ventana = new ManoDeObraIngeniero();
            control.activaVentana(ventana, this);
        }
    }//GEN-LAST:event_btnManoDeObraMouseClicked

    private void btnAgregarManoDeObraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarManoDeObraMouseClicked
        if(mat.vertamanomat()!=0||mob.vertamanomob()!=0||mhr.vertamanoher()!=0){
            AgregarManoDeObra ventana = new AgregarManoDeObra(mat,mob,mhr);
            control.activaVentana(ventana, this);
        }
        else{
            AgregarManoDeObra ventana = new AgregarManoDeObra();
            control.activaVentana(ventana, this);
        }  
    }//GEN-LAST:event_btnAgregarManoDeObraMouseClicked

    private void btnHerramientasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHerramientasMouseClicked
        if(mat.vertamanomat()!=0||mob.vertamanomob()!=0||mhr.vertamanoher()!=0){
            HerramientasIngeniero ventana = new HerramientasIngeniero(mat,mob,mhr);
            control.activaVentana(ventana, this);
        }
        else{
            HerramientasIngeniero ventana = new HerramientasIngeniero();
            control.activaVentana(ventana, this);
        } 
    }//GEN-LAST:event_btnHerramientasMouseClicked

    private void btnAgregarHerramientaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarHerramientaMouseClicked
        if(mat.vertamanomat()!=0||mob.vertamanomob()!=0||mhr.vertamanoher()!=0){
            AgregarHerramienta ventana = new AgregarHerramienta(mat,mob,mhr);
            control.activaVentana(ventana, this);
        }
        else{
            AgregarHerramienta ventana = new AgregarHerramienta();
            control.activaVentana(ventana, this);
        } 
    }//GEN-LAST:event_btnAgregarHerramientaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaIngeniero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaIngeniero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaIngeniero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaIngeniero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaIngeniero().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnAgregarHerramienta;
    private javax.swing.JPanel btnAgregarManoDeObra;
    private javax.swing.JPanel btnAgregarMaterial;
    private javax.swing.JPanel btnHerramientas;
    private javax.swing.JPanel btnManoDeObra;
    private javax.swing.JPanel btnMateriales;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
